package themes

import "image/color"

var TokyoNight = map[string]map[string]color.RGBA{
	"default": {
		"background":  hexToRGBA("#1a1b26"),
		"foreground":  hexToRGBA("#c0caf5"),
		"currentLine": hexToRGBA("#292e42"),
		"comment":     hexToRGBA("#565f89"),
		"red":         hexToRGBA("#f7768e"),
		"orange":      hexToRGBA("#ff9e64"),
		"yellow":      hexToRGBA("#e0af68"),
		"green":       hexToRGBA("#9ece6a"),
		"teal":        hexToRGBA("#61afef"),
		"blue":        hexToRGBA("#7aa2f7"),
		"purple":      hexToRGBA("#bb9af7"),
		"magenta":     hexToRGBA("#bb9af7"),
		"cyan":        hexToRGBA("#7dcfff"),
		"white":       hexToRGBA("#c0caf5"),
		"black":       hexToRGBA("#1a1b26"),
		"gray":        hexToRGBA("#565f89"),
	},
	"night": {
		"background":  hexToRGBA("#1a1b26"),
		"foreground":  hexToRGBA("#c0caf5"),
		"currentLine": hexToRGBA("#292e42"),
		"comment":     hexToRGBA("#565f89"),
		"red":         hexToRGBA("#f7768e"),
		"orange":      hexToRGBA("#ff9e64"),
		"yellow":      hexToRGBA("#e0af68"),
		"green":       hexToRGBA("#9ece6a"),
		"teal":        hexToRGBA("#61afef"),
		"blue":        hexToRGBA("#7aa2f7"),
		"purple":      hexToRGBA("#bb9af7"),
		"magenta":     hexToRGBA("#bb9af7"),
		"cyan":        hexToRGBA("#7dcfff"),
		"white":       hexToRGBA("#c0caf5"),
		"black":       hexToRGBA("#1a1b26"),
		"gray":        hexToRGBA("#565f89"),
	},
	"storm": {
		"background":  hexToRGBA("#24283b"),
		"foreground":  hexToRGBA("#a9b1d6"),
		"currentLine": hexToRGBA("#363b54"),
		"comment":     hexToRGBA("#444b6a"),
		"red":         hexToRGBA("#f7768e"),
		"orange":      hexToRGBA("#ff9e64"),
		"yellow":      hexToRGBA("#e0af68"),
		"green":       hexToRGBA("#9ece6a"),
		"teal":        hexToRGBA("#61afef"),
		"blue":        hexToRGBA("#7aa2f7"),
		"purple":      hexToRGBA("#bb9af7"),
		"magenta":     hexToRGBA("#bb9af7"),
		"cyan":        hexToRGBA("#7dcfff"),
		"white":       hexToRGBA("#a9b1d6"),
		"black":       hexToRGBA("#24283b"),
		"gray":        hexToRGBA("#444b6a"),
	},
	"light": {
		"background":  hexToRGBA("#e0e0e0"),
		"foreground":  hexToRGBA("#3a3a3a"),
		"currentLine": hexToRGBA("#d0d0d0"),
		"comment":     hexToRGBA("#808080"),
		"red":         hexToRGBA("#d65d0e"),
		"orange":      hexToRGBA("#e67a30"),
		"yellow":      hexToRGBA("#c18721"),
		"green":       hexToRGBA("#6d8721"),
		"teal":        hexToRGBA("#2a7a9a"),
		"blue":        hexToRGBA("#3b6ba5"),
		"purple":      hexToRGBA("#8e5c8e"),
		"magenta":     hexToRGBA("#8e5c8e"),
		"cyan":        hexToRGBA("#3e8c9c"),
		"white":       hexToRGBA("#3a3a3a"),
		"black":       hexToRGBA("#e0e0e0"),
		"gray":        hexToRGBA("#808080"),
	},
}
